# Generated by Django 5.0.1 on 2024-04-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_bookinstance_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="author",
            constraint=models.CheckConstraint(
                check=models.Q(("date_of_death__gt", models.F("date_of_birth"))),
                name="catalog_author_date_of_death_gt_date_of_birth",
            ),
        ),
    ]
